#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Sentence < Racc::Parser

module_eval(<<'...end sentence.y/module_eval...', 'sentence.y', 151)
  
  def parse(str)
    @q = []
    until str.empty?
      case str
      when /\A\s+/
      when /\A\w+/
        @q.push [$&, $&]
      when /\A./
        @q.push [$&, $&]
      end
      str = $'
    end
    @q.push [false, '$end']
    do_parse
  end

  def match(str)
    /\A#{str}/
  end

  def next_token
    @q.shift
  end

...end sentence.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    48,    49,    50,    51,    52,    53,    54,    55,    12,    13,
    14,    16,    17,    18,    19,    20,    21,    22,    23,    24,
    25,    26,    27,    28,    29,    30,    31,    77,    78,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    77,    78,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    71,    72,    73,    74,    75,    48,    49,    50,
    51,    52,    53,    54,    55,    77,    78,    12,    13,    14,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    48,
    49,    50,    51,    52,    53,    54,    55,    41,    84,   nil,
   nil,   nil,   nil,   nil,   nil,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    56,    57,    58,    59,    60,    61,
    62,    63,    64,    65,    66,    67,    68,    69,    70,    71,
    72,    73,    74,    75,   nil,   nil,    56,    57,    58,    59,
    60,    61,    62,    63,    64,    65,    66,    67,    68,    69,
    70,    71,    72,    73,    74,    75,    90,    91,    92,    93,
    94,    95,    96,    97,    98,    90,    91,    92,    93,    94,
    95,    96,    97,    98,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,    13,
    14,    16,    17,    18,    19,    20,    21,    22,    23,    24,
   nil,    99,   100,   101,   102,   103,   104,   nil,   nil,   nil,
    99,   100,   101,   102,   103,   104,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    12,    13,    14,    16,    17,
    18,    19,    20,    21,    22,    23,    24,   nil,   nil,   nil,
   nil,    20,    21,    22,    23,    24,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    20,    21,    22,    23,    24,   nil,   nil,   nil,   nil,
    20,    21,    22,    23,    24,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    32,    33,    34,    35,    36,    37,    38,    39,    40 ]

racc_action_check = [
    45,    45,    45,    45,    45,    45,    45,    45,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    79,    79,    79,    79,    79,    79,    79,     5,     5,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     4,     4,    45,    45,    45,
    45,    45,    45,    45,    45,    45,    45,    45,    45,    45,
    45,    45,    45,    45,    45,    45,    45,    88,    88,    88,
    88,    88,    88,    88,    88,   105,   105,    88,    88,    88,
    88,    88,    88,    88,    88,    88,    88,    88,    88,     3,
     3,     3,     3,     3,     3,     3,     3,     1,    41,   nil,
   nil,   nil,   nil,   nil,   nil,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,   nil,   nil,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,    86,    86,    86,    86,
    86,    86,    86,    86,    86,    43,    43,    43,    43,    43,
    43,    43,    43,    43,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
   nil,    86,    86,    86,    86,    86,    86,   nil,   nil,   nil,
    43,    43,    43,    43,    43,    43,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    44,    44,    44,    44,    44,
    44,    44,    44,    44,    44,    44,    44,   nil,   nil,   nil,
   nil,     9,     9,     9,     9,     9,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    44,    44,    44,    44,    44,    44,    44,
    44,    44,     9,     9,     9,     9,     9,     9,     9,     9,
     9,    80,    80,    80,    80,    80,   nil,   nil,   nil,   nil,
     8,     8,     8,     8,     8,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    80,    80,    80,    80,    80,    80,    80,    80,
    80,     8,     8,     8,     8,     8,     8,     8,     8,     8 ]

racc_action_pointer = [
    -4,    97,   nil,    87,    35,    17,   nil,   nil,   261,   222,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    98,   nil,   141,   213,    -2,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   176,   nil,   nil,   -13,
   252,   nil,   nil,   nil,   nil,   nil,   132,   nil,    65,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    65,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -2,  -106,    -1,  -106,    -4,    -5,    -7,    -9,  -106,  -106,
   -13,   -15,   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -49,
   -50,   -51,   -52,   -53,   -54,   -64,   -65,   -66,   -67,   -68,
   -69,   -70,   -71,   -72,   -73,   -74,   -75,   -76,   -77,   -78,
   -79,  -106,    -3,   -25,   -19,  -106,   -21,   -23,   -32,   -33,
   -34,   -35,   -36,   -37,   -38,   -39,   -80,   -81,   -82,   -83,
   -84,   -85,   -86,   -87,   -88,   -89,   -90,   -91,   -92,   -93,
   -94,   -95,   -96,   -97,   -98,   -99,  -106,   -40,   -41,  -106,
  -106,   -11,   -12,   -14,   116,   -16,   -24,   -27,  -106,   -29,
   -55,   -56,   -57,   -58,   -59,   -60,   -61,   -62,   -63,  -100,
  -101,  -102,  -103,  -104,  -105,   -18,   -17,   -20,   -22,    -8,
    -6,   -10,   -26,   -28,   -30,   -31 ]

racc_goto_table = [
    43,     6,    81,    82,    83,     4,   109,    87,     1,     5,
    80,    79,    42,     3,    85,   106,   107,   108,   114,    86,
     2,   113,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   105,
   112,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   111,    83,   nil,   nil,   nil,   nil,
   110,   nil,   nil,   nil,   nil,   115 ]

racc_goto_check = [
    14,     8,    12,    12,    13,     5,     9,    22,     1,     6,
    11,     7,     4,     3,    15,    17,    19,    20,     9,    21,
     2,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,
    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    12,    13,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,     8,    20,    13,     9,     5,     9,     6,     1,   -70,
   nil,     2,    -6,    -5,    -3,   -29,   nil,   -29,   nil,   -29,
   -28,   -24,   -36,   nil,   -67,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    76,   nil,     7,
     8,     9,    10,    11,   nil,   nil,    44,   nil,    45,    46,
    47,   nil,   nil,    88,   nil,    89,    15 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 76, :_reduce_1,
  0, 76, :_reduce_none,
  2, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  3, 81, :_reduce_none,
  1, 81, :_reduce_none,
  3, 80, :_reduce_none,
  1, 80, :_reduce_none,
  3, 84, :_reduce_none,
  2, 84, :_reduce_none,
  2, 84, :_reduce_none,
  1, 84, :_reduce_none,
  2, 86, :_reduce_none,
  1, 86, :_reduce_none,
  2, 79, :_reduce_none,
  2, 89, :_reduce_none,
  1, 92, :_reduce_none,
  0, 92, :_reduce_none,
  2, 91, :_reduce_none,
  1, 91, :_reduce_none,
  2, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 90, :_reduce_none,
  0, 90, :_reduce_none,
  2, 96, :_reduce_none,
  1, 96, :_reduce_none,
  2, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 99, :_reduce_none,
  1, 99, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 95, :_reduce_none,
  1, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none ]

racc_reduce_n = 106

racc_shift_n = 116

racc_token_table = {
  false => 0,
  :error => 1,
  "merrily" => 2,
  "quickly" => 3,
  "gracefully" => 4,
  "thoughtfully" => 5,
  "everyday" => 6,
  "sometimes" => 7,
  "always" => 8,
  "never" => 9,
  "," => 10,
  "and" => 11,
  "a" => 12,
  "an" => 13,
  "the" => 14,
  "my" => 15,
  "our" => 16,
  "your" => 17,
  "their" => 18,
  "funny" => 19,
  "cute" => 20,
  "fast" => 21,
  "happy" => 22,
  "some" => 23,
  "to" => 24,
  "through" => 25,
  "toward" => 26,
  "down" => 27,
  "on" => 28,
  "under" => 29,
  "around" => 30,
  "in" => 31,
  "near" => 32,
  "I" => 33,
  "he" => 34,
  "she" => 35,
  "it" => 36,
  "they" => 37,
  "you" => 38,
  "we" => 39,
  "mom" => 40,
  "dog" => 41,
  "cat" => 42,
  "store" => 43,
  "car" => 44,
  "house" => 45,
  "street" => 46,
  "eggs" => 47,
  "milk" => 48,
  "walk" => 49,
  "buy" => 50,
  "go" => 51,
  "get" => 52,
  "fly" => 53,
  "like" => 54,
  "want" => 55,
  "walks" => 56,
  "gets" => 57,
  "likes" => 58,
  "buys" => 59,
  "goes" => 60,
  "flies" => 61,
  "wants" => 62,
  "walked" => 63,
  "bought" => 64,
  "went" => 65,
  "flew" => 66,
  "wanted" => 67,
  "got" => 68,
  "walking" => 69,
  "eating" => 70,
  "buying" => 71,
  "flying" => 72,
  "being" => 73,
  "wanting" => 74 }

racc_nt_base = 75

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"merrily\"",
  "\"quickly\"",
  "\"gracefully\"",
  "\"thoughtfully\"",
  "\"everyday\"",
  "\"sometimes\"",
  "\"always\"",
  "\"never\"",
  "\",\"",
  "\"and\"",
  "\"a\"",
  "\"an\"",
  "\"the\"",
  "\"my\"",
  "\"our\"",
  "\"your\"",
  "\"their\"",
  "\"funny\"",
  "\"cute\"",
  "\"fast\"",
  "\"happy\"",
  "\"some\"",
  "\"to\"",
  "\"through\"",
  "\"toward\"",
  "\"down\"",
  "\"on\"",
  "\"under\"",
  "\"around\"",
  "\"in\"",
  "\"near\"",
  "\"I\"",
  "\"he\"",
  "\"she\"",
  "\"it\"",
  "\"they\"",
  "\"you\"",
  "\"we\"",
  "\"mom\"",
  "\"dog\"",
  "\"cat\"",
  "\"store\"",
  "\"car\"",
  "\"house\"",
  "\"street\"",
  "\"eggs\"",
  "\"milk\"",
  "\"walk\"",
  "\"buy\"",
  "\"go\"",
  "\"get\"",
  "\"fly\"",
  "\"like\"",
  "\"want\"",
  "\"walks\"",
  "\"gets\"",
  "\"likes\"",
  "\"buys\"",
  "\"goes\"",
  "\"flies\"",
  "\"wants\"",
  "\"walked\"",
  "\"bought\"",
  "\"went\"",
  "\"flew\"",
  "\"wanted\"",
  "\"got\"",
  "\"walking\"",
  "\"eating\"",
  "\"buying\"",
  "\"flying\"",
  "\"being\"",
  "\"wanting\"",
  "$start",
  "target",
  "sentence",
  "subject",
  "predicate",
  "descriptive_noun_list",
  "pronoun_list",
  "conjunction",
  "pronoun",
  "descriptive_noun",
  "article",
  "adjective_list",
  "noun",
  "adjective",
  "direct_object_clause",
  "opt_prepositional_phrase_list",
  "descriptive_verb",
  "direct_object",
  "adverb_list",
  "verb",
  "adverb",
  "prepositional_phrase_list",
  "prepositional_phrase",
  "preposition",
  "object_of_preposition",
  "present_participle",
  "possessive_pronoun" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'sentence.y', 3)
  def _reduce_1(val, _values, result)
     result = "You entered a valid sentence."
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Sentence


parser = Sentence.new
while true
  puts
  print '> '
  str = gets.chop!
  break if /q/i =~ str
  begin
    puts "= #{parser.parse(str)}"
  rescue ParseError
    puts "Sorry, that is not a valid sentence."
    puts $!
  end
end
